list: $/elisseiidev/branchmanagement/models/cities/columns.yaml
modelClass: Elisseiidev\BranchManagement\Models\Cities
title: Cities
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: false
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'elisseiidev/branchmanagement/cities/update/:id'
